export const CUSTOMER_AUTH_SMS_COUNTDOWN_SECONDS = 60;
export const CUSTOMER_COMPANY_NAME_MAX_LENGTH = 100;
export const CUSTOMER_INFO_STORAGE_KEY = 'MYJOB_CUSTOMER_INFO';
export const CUSTOMER_TOKEN_STORAGE_KEY = 'MYJOB_CUSTOMER_TOKEN';
